name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2	
      - name: run a script
        run: env
 
      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          export NEWNAME=$(echo "$GITHUB_REPOSITORY" | sed "s/\//-/g")
          sed -i "s/git_owner/$NEWNAME/g" map.json 
          sed -i "s/GIT_OWNER/$NEWNAME/g" map.json 
          cat map.json
          ls -al
          git config --global user.email "d.negrier@thecodingmachine.com"
          git config --global user.name "David Négrier"
          git checkout master
          git commit -am "Adding files"

         
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master

      - name: Bash2
        run: |
          ls -al
          export NEWNAME=$(echo "$GITHUB_REPOSITORY" | sed "s/\//-/g")
          sed -i "s/git_owner/$NEWNAME/g" map.json 
          sed -i "s/GIT_OWNER/$NEWNAME/g" map.json 
          cat map.json
 
